# -*- coding: utf-8 -*-
"""miniprojectsem6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d15bHWytkJQ8djkSxP8atVrFjXawc8wA
"""

import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix



df = pd.read_csv("enhanced_student_habits_performance_dataset.csv")

print(df.isnull().sum())

numeric_cols = df.select_dtypes(include=np.number).columns
object_cols = df.select_dtypes(include='object').columns

for col in numeric_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

for col in object_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

df = df.fillna(df.mode().iloc[0])

import numpy as np
print(np.isinf(X).sum())

X = np.nan_to_num(X)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)

model.compile(
    optimizer=optimizer,
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

df["procrastination_score"] = (
    0.25 * df["social_media_hours"] +
    0.20 * df["netflix_hours"] +
    0.20 * df["screen_time"] +
    0.15 * (10 - df["study_hours_per_day"]) +
    0.10 * (100 - df["attendance_percentage"]) / 10 +
    0.10 * (10 - df["time_management_score"])
)

low_threshold = df["procrastination_score"].quantile(0.33)
high_threshold = df["procrastination_score"].quantile(0.66)

def categorize(score):
    if score < low_threshold:
        return "Low"
    elif score < high_threshold:
        return "Medium"
    else:
        return "High"

df["procrastination_level"] = df["procrastination_score"].apply(categorize)

df_model = df.drop([
    "student_id",
    "procrastination_score",
    "procrastination_level"
], axis=1)

X = df_model
y = df["procrastination_level"]

X = pd.get_dummies(X, drop_first=True)

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(tf.keras.layers.Dense(32, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Train", "Validation"])
plt.show()

import numpy as np

# Predict probabilities
y_pred_prob = model.predict(X_test)

# Convert probabilities → class index
y_pred = np.argmax(y_pred_prob, axis=1)

print("Predicted classes:", y_pred[:10])

predicted_labels = label_encoder.inverse_transform(y_pred)

print("Predicted labels:", predicted_labels[:10])

new_student_data_raw = pd.DataFrame([{
    "study_hours_per_day": 10,
    "social_media_hours": 0,
    "netflix_hours": 1,
    "attendance_percentage": 90,
    "screen_time": 2,
    "motivation_level": 7,
    "time_management_score": 3,
    "exam_score": 90,
    "stress_level": 8,
    "exam_anxiety_score": 6,

    "age": 20,
    "gender": "Male",
    "major": "Computer Science",

    "diet_quality": "Good",
    "exercise_frequency": "Often",
    "parental_education_level": "University",
    "internet_quality": "Good",
    "mental_health_rating": 4,
    "extracurricular_participation": "Yes",
    "previous_gpa": 4.0,
    "semester": "Fall",
    "dropout_risk": "No",
    "social_activity": "Active",
    "study_environment": "Home",
    "access_to_tutoring": "No",
    "family_income_range": "Medium",
    "learning_style": "Auditory"
}])


encoded_training_columns = pd.get_dummies(df_model, drop_first=True).columns


new_student_encoded = pd.get_dummies(new_student_data_raw, drop_first=True)


new_student_aligned = new_student_encoded.reindex(columns=encoded_training_columns, fill_value=0)


new_student_scaled = scaler.transform(new_student_aligned)


prediction = model.predict(new_student_scaled)
prediction_class = np.argmax(prediction, axis=1)

final_prediction = label_encoder.inverse_transform(prediction_class)

print("Predicted Procrastination Level:", final_prediction[0])